name: Test-Secrets

on:
  push:
    branches:
      - master

env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT}}

jobs:
  testsecrets:
    name: Test Secrets
    runs-on: ubuntu-latest
    steps:
    - run: |-
        echo "Hello World!"
        echo "Hello Again!"
        echo ${{ secrets.GKE_PROJECT }} | base64
        echo $GKE_PROJECT
        npm version
        #echo $GKE_SA_KEY | base64
# jobs:
#   testsecret:
#     runs-on: ubuntu-latest
#     steps:
#     - run: |-
#         echo ${{secrets.GKE_PROJECT}} | base64
#         echo ${{secrets.GKE_SA_KEY}}
#         echo hello
