name: Test

on:
  push:
    branches:
      - master

env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

jobs:
  testsecrets:
    name: Test Secrets
    runs-on: ubuntu-latest
    steps:
    - run: |-
        echo ${{ secrets.GKE_PROJECT }}
# jobs:
#   testsecret:
#     runs-on: ubuntu-latest
#     steps:
#     - run: |-
#         echo ${{secrets.GKE_PROJECT}} | base64
#         echo ${{secrets.GKE_SA_KEY}}
#         echo hello